### ISSUE TITLE
An error occurs when running "download.sh"

### ISSUE THREAD

**Issue by ZouXinn** [Jingkang50/OpenOOD#202]
I met an error as below when I ran the file "download.sh":

```
Traceback (most recent call last):
  File "./scripts/download/download.py", line 190, in <module>
    gdown.download(id=download_id_dict['benchmark_imglist'],
  File "/home/zx/.conda/envs/OpenOOD/lib/python3.8/site-packages/gdown/download.py", line 146, in download
    res = sess.get(url, headers=headers, stream=True, verify=verify)
  File "/home/zx/.conda/envs/OpenOOD/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/zx/.conda/envs/OpenOOD/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zx/.conda/envs/OpenOOD/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/zx/.conda/envs/OpenOOD/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b46cbe20>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

Does someone have a solution?

**Comment by ZouXinn** [comment]
Seems like my network is bad?

**Comment by ZouXinn** [comment]
Is it because of the Great Firewall of China?

**Comment by zjysteven** [comment]
Could be. Try using a VPN or first download to local and then upload to the server.

**Comment by ZouXinn** [comment]
Thank you for your suggestion.
